apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "backend-pc"
      containers:
        - name: backend
          image: 008971675165.dkr.ecr.us-west-1.amazonaws.com/backend:latest
          ports:
          - containerPort: 8888
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          # env:
          # - name: DB_NAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: fullstack
          #       key: dbname
          # - name: DB_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: fullstack
          #       key: host
          # - name: DB_PORT
          #   valueFrom:
          #     secretKeyRef:
          #       name: fullstack
          #       key: port
          # - name: DB_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: fullstack
          #       key: username
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: fullstack
          #       key: password