apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: fullstackloadgen
      containers:
        - name: backend
          image: fullstackloadgen.azurecr.io/backend:latest
          ports:
          - containerPort: 8888
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db-login
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db-password