apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fullstackloadgen
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: c45c4afb-fde5-4ace-b3ba-fc5263abe4be
    keyvaultName: "fullstackloadgen"               
    objects:  |
      array:
        - |
          objectName: CosmosDBConnectionString
          objectType: key
    tenantID: ${ARM_TENANT_ID}