apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-pc
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "fullstack-loadgen"
        objectType: "secretsmanager"
        objectAlias: backend-creds
        jmesPath: 
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
          - path: host
            objectAlias: host
          - path: port
            objectAlias: port
          - path: dbname
            objectAlias: dbname
  secretObjects:
  - secretName: realsecrets
    type: Opaque
    data:
    - objectName: username
      key: username
    - objectName: password
      key: password
    - objectName: host
      key: host
    - objectName: port
      key: port
    - objectName: dbname
      key: dbname
