apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-pc
spec:
  provider: aws
  parameters:
    region: us-west-1
    objects: |
        - objectName: "fullstack-loadgen"
          objectType: "secretsmanager"
  secretObjects:
  - secretName: fullstack-loadgen
    type: Opaque
    data: 
    - objectName: username
      key: username
    - objectName: password
      key: password
    - objectName: host
      key: host
    - objectName: port
      key: port
    - objectName: dbname
      key: dbname
      