apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    # usePodIdentity: "false"               # [OPTIONAL] if not provided, will default to "false"
    # useVMManagedIdentity: "false"         # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    # userAssignedIdentityID: "client_id"   # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    clientID: ${ARM_CLIENT_ID}                 # [OPTIONAL available for version > 1.1.0] client id of the Azure AD Application or managed identity to use for workload identity
    keyvaultName: "fullstackloadgen"                # the name of the KeyVault
    # cloudName: ""                         # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    # cloudEnvFileName: ""                  # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects:  |
      array:
        - |
          objectName: test123
          objectType: key
    tenantID: ${ARM_TENANT_ID}                       # the tenant ID of the KeyVault
 
 # objectAlias: ""                 # If provided then it has to be referenced in [secretObjects].[objectName] to sync with Kubernetes secrets 

# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: backend-pc
# spec:
#   provider: aws
#   parameters:
#     objects: |
#       - objectName: "fullstack-loadgen"
#         objectType: "secretsmanager"
#         objectAlias: realsecrets

#        # jmesPath: 
        #   - path: username
        #     objectAlias: username
        #   - path: password
        #     objectAlias: password
        #   - path: host
        #     objectAlias: host
        #   - path: port
        #     objectAlias: port
        #   - path: dbname
        #     objectAlias: dbname
  # secretObjects:
  # - secretName: realsecrets
  #   type: Opaque
  #   data:
  #   - objectName: username
  #     key: username
  #   - objectName: password
  #     key: password
  #   - objectName: host
  #     key: host
  #   - objectName: port
  #     key: port
  #   - objectName: dbname
  #     key: dbname
