apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fullstackloadgen
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: ${SECRETS_IDENTITY_ID}
    keyvaultName: "fullstackloadgen"               
    objects:  |
      array:
        - |
          objectName: db_password
          objectType: secret
        - |
          objectName: db_username
          objectType: secret
    tenantID: ${ARM_TENANT_ID}