apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fullstackloadgen
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: bc599c54-ba93-4359-b143-ad4e69765b01
    keyvaultName: "fullstackloadgen"               
    objects:  |
      array:
        - |
          objectName: CosmosDBConnectionString
          objectType: key
    tenantID: ${ARM_TENANT_ID}