apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    clientID: ${ARM_CLIENT_ID}
    keyvaultName: "fullstackloadgen"               
    objects:  |
      array:
        - |
          objectName: test123
          objectType: key
    tenantID: ${ARM_TENANT_ID}