apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fullstackloadgen
spec:
  provider: azure
  parameters:
    clientID: ${ARM_CLIENT_ID}
    userAssignedIdentityID: b759bfca-9bd7-48ee-87d2-f6ae70f02c81
    keyvaultName: "fullstackloadgen"               
    objects:  |
      array:
        - |
          objectName: CosmosDBConnectionString
          objectType: key
    tenantID: ${ARM_TENANT_ID}