name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t frontend ./frontend
          docker build -t backend ./backend
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag frontend bggridley/frontend:latest
          docker push bggridley/frontend:latest
          docker tag backend bggridley/backend:latest
          docker push bggridley/backend:latest