name: 'Terraform'

on:
  push:
    branches:
      - terraform
permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Change directory to iac/terraform
        run: cd iac/terraform

      - name: Terraform Init
        run: |
          terraform init
          terraform plan
          terraform destroy -auto-approve
        working-directory: iac/terraform
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
