name: 'Terraform'

on:
  push:
    branches:
      - terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show
      #       az storage -h
      - name: Change directory to iac/terraform
        run: cd iac/terraform

      - name: Terraform Init
        run: terraform init
        working-directory: iac/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: iac/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: iac/terraform
